#!/usr/bin/env python3
"""Compare uid/gid-map indirect-call type IDs to file_ns_capable in the Image.

This checks ARM64 KCFI code generated by the target compiler; it is deliberately
specific to the map writer, whose two checked indirect calls use that API.
"""
import argparse
from pathlib import Path
import struct


def function_bytes(path, wanted):
    data = path.read_bytes()
    if data[:6] != b"\x7fELF\x02\x01" or struct.unpack_from("<H", data, 18)[0] != 183:
        raise ValueError("Expected an ARM64 ELF64 object")
    offset = struct.unpack_from("<Q", data, 40)[0]
    size, count = struct.unpack_from("<HH", data, 58)
    headers = [struct.unpack_from("<IIQQQQIIQQ", data, offset + i * size)
               for i in range(count)]
    for header in headers:
        if header[1] != 2:
            continue
        linked = headers[header[6]]
        names = data[linked[4]:linked[4] + linked[5]]
        for pos in range(header[4], header[4] + header[5], header[9]):
            name, _, _, section, address, length = struct.unpack_from("<IBBHQQ", data, pos)
            if names[name:names.index(0, name)].decode() == wanted:
                text = headers[section]
                start = text[4] + address - text[3]
                return data[start:start + length]
    raise ValueError("Map writer symbol missing")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("image", type=Path)
    parser.add_argument("system_map", type=Path)
    parser.add_argument("proc_object", type=Path)
    args = parser.parse_args()
    symbols = {row.split()[2]: int(row.split()[0], 16)
               for row in args.system_map.read_text().splitlines()}
    offset = symbols["file_ns_capable"] - symbols["_text"] - 4
    native = struct.unpack_from("<I", args.image.read_bytes(), offset)[0]
    text = function_bytes(args.proc_object, "droid_lkm_userns_map_write")
    hashes, parts = [], {}
    for (insn,) in struct.iter_unpack("<I", text):
        # MOVK W17,#imm16,LSL #0/#16 followed by CMP W16,W17.
        if insn & 0xffc0001f == 0x72800011:
            parts[(insn >> 21) & 1] = (insn >> 5) & 0xffff
        if insn == 0x6b11021f:
            if parts.keys() != {0, 1}:
                raise ValueError("Unrecognized KCFI code sequence")
            hashes.append(parts[0] | parts[1] << 16)
            parts = {}
    if len(hashes) != 2 or any(value != native for value in hashes):
        formatted = ", ".join(f"{value:#010x}" for value in hashes)
        parser.exit(1, f"FAIL: kernel file_ns_capable={native:#010x}, map call types=[{formatted}]\n")
    print(f"PASS: both map-call KCFI types match phone file_ns_capable: {native:#010x}")


if __name__ == "__main__":
    main()
